server:
  port: 8001
  servlet:
    context-path: /member
# 数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: train
    url: jdbc:mysql://localhost:3306/train_member?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train
# mybatis xml路径
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    org:
      feather:
        train:
          member:
            mapper: trace

